### ISSUE TITLE
Active repo? License?

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/open-forcefield-group#5]
Is this repo still being used for anything? If so, is the intention to really have it as GPL, or should we migrate to another license (such as MIT) more consistent with OpenMM? https://github.com/open-forcefield-group/smarty/issues/163

**Comment by jchodera** [comment]
This is just a dumping ground for some ideas and data right now.

MIT is fine. Can you add it?

**Comment by jchodera** [comment]
Thanks, @davidlmobley !
